#2 reuse pages from older website
rp-js/rpjs-website pull request #23
Opened 2023-06-02 16:12 UTC by Jbnado

close #2

2023-06-02 16:17 UTC, RenanRSilva approved these changes

2023-06-02 16:22 UTC, PedroLuisBrilhadori requested changes

2023-06-02 16:22 UTC, PedroLuisBrilhadori commented on src/app/components/social-media-button-component.tsx
> +        </li> */}
os comentários são necessários?

2023-06-02 16:22 UTC, PedroLuisBrilhadori commented on src/app/components/speaker-card-component.tsx
> +        alt={name + role}
aqui poderia ter um espaço para que não fique "JoaoFullstack"

2023-06-04 18:23 UTC, RenanRSilva approved these changes

2023-06-04 18:30 UTC, PedroLuisBrilhadori approved these changes

2023-06-04 23:43 UTC, merged